### ISSUE TITLE
Suggest tqdm for download_data

### ISSUE THREAD

**Issue by IanHawke** [duetosymmetry/qnm#11]
On first running it's unclear how long the `qnm.download_data()` will take. Could use `tqdm` (https://tqdm.github.io/) as a progress bar to make this clearer.

**Comment by duetosymmetry** [comment]
Here's a general question... is it reasonable to add tqdm as a requirement, though it's not really necessary to use the package? Or am I supposed to be using try/except at runtime to see if the user has tqdm, and fallback to no status output if they don't already have it?

**Comment by IanHawke** [comment]
That's a tricky one. I think of tqdm as a "standard" module like numpy and so would have no problem with it as a requirement, but I'm not sure how it's generally viewed. Also, given the standard way that it's used as a decorator, I don't think try/except is practical.

**Comment by duetosymmetry** [comment]
Merged into master.
