### ISSUE TITLE
Location of on-disk cache

### ISSUE THREAD

**Issue by duetosymmetry** [duetosymmetry/qnm#20]
We can follow the model used by matplotlib:
- Function like `qnm.get_configdir()` which has a default value, that can be overridden by an ENV var named something like QNMCONFIGDIR. If this dir exists (default `$HOME/.qnm`) and has a config file (`qnm.cfg`) it will be parsed using [`configparser`](https://docs.python.org/3/library/configparser.html).
- Function like `qnm.get_cachedir()` which had a default value, that can be overridden by a value in the above config file. Not sure if the default should be in the package's install directory or in the user's home dir like `$HOME/.qnm`. This is where `qnm.download_data()` should try to save the downloaded cache. Question: What if the cache structure changes with a package update?

**Comment by duncanmmacleod** [comment]
Hi @duetosymmetry, coming here from https://github.com/openjournals/joss-reviews/issues/1683, the location and handling of the cache is my largest concern with this package (I have no concerns with the scientific content of the package).

With regards to cache location:

(IMO) This package must not rely upon write access to the installation directory, which will render administrator control and user utility of the package impossible. I strongly suggest you consider following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which would place the cache in `~/.cache/qnm/`. As you mention matplotlib has good support for this, inspiration could be taken (with appropriate credit) from https://github.com/matplotlib/matplotlib/blob/v3.1.1/lib/matplotlib/__init__.py#L512-L610

With regards to updating the cache:

You might want to consider versioning the remote cache data, e.g. https://duetosymmetry.com/files/qnm/data-1.0.0.tar.bz2 and pinning the data version to the package version, giving you the freedom to reformat the data and then release a new version of both the data and the package that can handle it.

**Comment by duetosymmetry** [comment]
Tests now pass, closing.
