### ISSUE TITLE
How to calculate the frequency when mass is not 1?

### ISSUE THREAD

**Issue by Editi0** [duetosymmetry/qnm#24]
Could you please tell me how to calculate the frequency when the mass of remnant object is not 1?

**Comment by duetosymmetry** [comment]
Hi, no special code is needed for this. Just use the fact that the Kerr solution can be scaled up/down by the mass parameter. So, what the code is computing is not really omega, but rather the dimensionless combination M*omega (i.e. dimensionless in geometric units, where [M]=[L]=[T]). So, give the code the value of dimensionless spin chi = J/M^2 = a/M, where 0 <= chi < 1; the code will give you the product (M*omega), and then you can divide by your M to get the physical omega.
